### ISSUE TITLE
Problems running pytest

### ISSUE THREAD

**Issue by cudmore** [mapmanager/brightest-path-lib#40]
I am trying to follow the recipe for running pytest on brightest-path-lib but am getting errors. I am on macOS [edit: an m1 arm mac].

I do the following

    cd brightest-path-lib
    python -m venv brightest-venv
    source brightest-venv/bin/activate
    pip install -e '.[test]'

Then run `pytest` and I get the following error (See below).

Could this be because I am making a venv from a miniconda version of Python? We should assume users might be doing this.

```
(brightest-venv) (base) cudmore brightest-path-lib:pytest tests
Traceback (most recent call last):
  File "/Users/cudmore/opt/miniconda3/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/_pytest/config/__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/_pytest/config/__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/_pytest/helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1016, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1187, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/napari/utils/__init__.py", line 1, in <module>
    from ._dask_utils import resize_dask_cache
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/napari/utils/_dask_utils.py", line 8, in <module>
    import dask.array as da
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/dask/array/__init__.py", line 2, in <module>
    from dask.array import backends, fft, lib, linalg, ma, overlap, random
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/dask/array/backends.py", line 6, in <module>
    from dask.array.core import Array
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/dask/array/core.py", line 37, in <module>
    from dask.array.chunk_types import is_valid_array_chunk, is_valid_chunk_type
  File "/Users/cudmore/opt/miniconda3/lib/python3.9/site-packages/dask/array/chunk_types.py", line 131, in <module>
    register_chunk_type(scipy.sparse.spmatrix)
AttributeError: module 'scipy.sparse' has no attribute 'spmatrix'
```

**Comment by cudmore** [comment]
Aha, I ran into the same problem running Napari. It is a persistent problem on M1 arm macOS. I always forget.

Running from a conda environment did not produce an error.

I will add this to the documentation.

**Comment by cudmore** [comment]
On M1 macOS, need to install in a conda environment.
